/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallDetail: typeof import('./src/components/callDetail/index.vue')['default']
    CallDialog: typeof import('./src/components/callDialog/index.vue')['default']
    CallFreeDialog: typeof import('./src/components/callFreeDialog/index.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    FirstChargeVipPopup: typeof import('./src/components/firstChargeVipPopup/index.vue')['default']
    GiftPopup: typeof import('./src/components/giftPopup/index.vue')['default']
    RechargePopup: typeof import('./src/components/rechargePopup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignPopup: typeof import('./src/components/signPopup/index.vue')['default']
    SvgaDialog: typeof import('./src/components/svgaDialog/index.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    VipPopup: typeof import('./src/components/vipPopup/index.vue')['default']
  }
}
