FROM --platform=linux/amd64 ccr.ccs.tencentyun.com/borders/ant-builder:1 as builder

ADD . /webapp/

WORKDIR /webapp

#RUN npm install -g nrm && nrm use taobao  &&
RUN npm install && npm run build:prod

EXPOSE 8000
ENTRYPOINT ["npm" ,"run","start:prod"]


FROM --platform=linux/amd64 nginx
COPY --from=builder /webapp/dist/ /usr/share/nginx/html


